import { test } from "node:test";
import assert from "node:assert/strict";
import { clampPrompt, substantivePrompt } from "../src/server/transcript.ts";

// Every fixture below is a real shape lifted from this machine's transcripts or from the
// daemon's own `session_events`, not an invented one - the filter exists because 53% of
// real UserPromptSubmit events carry no human words at all.

test("a background task reporting in is not a goal", () => {
  // The single biggest noise source: 200 of 396 real UserPromptSubmit events (51%).
  const raw =
    "<task-notification>\n<task-id>bkwkl0pl0</task-id>\n" +
    "<tool-use-id>toolu_01JhYwkSj5sYgvNYiHYcowMR</tool-use-id>\n" +
    "<status>failed</status>\n<summary>Background command failed with exit code 1</summary>\n" +
    "</task-notification>";
  assert.equal(substantivePrompt(raw), null);
});

test("a slash command survives as the words the human typed", () => {
  const raw =
    "<local-command-caveat>Caveat: The messages below were generated by the user while " +
    "running local commands. DO NOT respond to these messages.</local-command-caveat>\n" +
    "<command-name>/no-mistakes</command-name>\n" +
    "<command-message>no-mistakes</command-message>\n" +
    "<command-args>the changes for tab select, arrow movement, and hot keys</command-args>";
  // The args are the whole ask here; dropping them would leave a far worse sentence.
  assert.equal(
    substantivePrompt(raw),
    "/no-mistakes the changes for tab select, arrow movement, and hot keys",
  );
});

test("the transcript and the hook agree on what a slash command asked", () => {
  // The same command reaches Tier 1 as the flat string the human typed and Tier 2 wrapped in
  // tags. If these disagreed, a goal would change meaning purely by which tier last wrote it.
  const viaTranscript = substantivePrompt(
    "<local-command-caveat>Caveat: ...</local-command-caveat>\n" +
      "<command-name>/no-mistakes</command-name>\n<command-message>no-mistakes</command-message>\n" +
      "<command-args>fix the arrow keys</command-args>",
  );
  assert.equal(viaTranscript, "/no-mistakes fix the arrow keys");
  assert.equal(viaTranscript, substantivePrompt("/no-mistakes fix the arrow keys"));
});

test("a session-control command is never a goal", () => {
  // `/clear` and `/compact` act on the session, not on the work. They pass every other test
  // here - a human really did type them - so they need naming explicitly.
  //
  // This matters for the transcript path, not the hook path: a /clear mints a new session
  // whose transcript OPENS with the clear echo (169 of 198 sampled files), so a reader taking
  // the first substantive turn of a freshly cleared session would otherwise read "/clear".
  for (const raw of ["/clear", "/compact", "/compact focus on the tests"]) {
    assert.equal(substantivePrompt(raw), null, `${raw} became a goal`);
  }
  const viaTranscript =
    "<local-command-caveat>Caveat: ...</local-command-caveat>\n" +
    "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n" +
    "<command-args></command-args>";
  assert.equal(substantivePrompt(viaTranscript), null, "/clear became a goal via the transcript");
});

test("a work command that merely starts like a meta one is still a goal", () => {
  // The rule is anchored and word-bounded, so it can't eat a real command or real prose.
  assert.equal(substantivePrompt("/clear-cache the stale build"), "/clear-cache the stale build");
  assert.equal(substantivePrompt("clear the goal when a session is cleared"), "clear the goal when a session is cleared");
});

test("prose wrapped in scaffolding keeps only the prose", () => {
  // Real shape: the caveat block is embedded in, not instead of, the turn (121 of 236
  // sampled occurrences).
  const raw =
    "<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>\n" +
    "fix the worktree cleanup bug in Reset\n" +
    "<system-reminder>Today's date is 2026-07-15.</system-reminder>";
  assert.equal(substantivePrompt(raw), "fix the worktree cleanup bug in Reset");
});

test("Claude's own local-command echo is not a goal", () => {
  assert.equal(substantivePrompt("Set effort level to xhigh"), null);
  assert.equal(substantivePrompt("[Request interrupted by user for tool use]"), null);
});

test("an ordinary typed prompt passes through intact", () => {
  const raw = "continue implementation for docs/plans/goals/plan.md";
  assert.equal(substantivePrompt(raw), raw);
});

test("an empty or whitespace-only prompt yields null, not an empty goal", () => {
  for (const raw of [null, undefined, "", "   \n  "]) {
    assert.equal(substantivePrompt(raw), null, `expected null for ${JSON.stringify(raw)}`);
  }
});

test("a long typed prompt is NOT rejected for its length", () => {
  // p90 of real clean first prompts is 5,515 chars. The plan's original "implausibly long"
  // rule would have discarded exactly the most detailed asks - the ones with the clearest
  // goal - so it was dropped. This pins that.
  const long = `refactor the registry so that ${"a really specific requirement, ".repeat(400)}`;
  assert.ok(long.length > 6000);
  assert.equal(substantivePrompt(long), long.trim());
});

test("an unclosed tag a human typed does not swallow their prompt", () => {
  // Matching to end-of-string would delete this entire ask.
  const raw = "why does <command-name> show up in the goal? fix it";
  assert.equal(substantivePrompt(raw), raw);
});

test("a machine block truncated mid-way is still not a goal", () => {
  // Real shape, straight out of `session_events`, which stores the 120-char trimmed
  // activity - so the block is cut off and never closes. The closed-block rule alone does
  // nothing here and the whole notification would land on a card as its goal.
  const raw =
    "<task-notification> <task-id>byc4fw3pc</task-id> " +
    "<tool-use-id>toolu_01RWhJDPbJbJiqrcYBerv9qX</tool-use-id> <ou…";
  assert.equal(substantivePrompt(raw), null);
});

test("a caveat block still yields the prose that follows it", () => {
  // Guards the ordering: the truncation rule above must not fire on a CLOSED leading block,
  // which is the common shape (121 of 236 sampled occurrences are followed by a real ask).
  const raw = "<local-command-caveat>Caveat: ...</local-command-caveat>\nfix the reset bug";
  assert.equal(substantivePrompt(raw), "fix the reset bug");
});

test("clampPrompt keeps the ask when it trails a huge paste", () => {
  // Head-only truncation would store the log and lose the question entirely.
  const ask = "work out why this breaks";
  const text = `here is the failing log:\n${"x".repeat(9000)}\n${ask}`;
  const out = clampPrompt(text);
  assert.ok(out.length < text.length, "over-cap prompt was not clamped");
  assert.ok(out.startsWith("here is the failing log:"), "lost the head");
  assert.ok(out.endsWith(ask), "lost the ask at the tail");
  assert.ok(out.includes("[…]"), "elision is not marked");
});

test("clampPrompt leaves an ordinary prompt untouched", () => {
  const text = "fix the flaky test in foreman-review";
  assert.equal(clampPrompt(text), text);
});
