import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const home = mkdtempSync(join(tmpdir(), 'mission-dashboard-health-'));
process.env.MISSION_HOME = home;
const { openDb, closeDb } = await import('../src/server/db.ts');
const { captureTelemetryHealth } = await import('../src/server/telemetry/health.ts');
const { setTelemetryConfig } = await import('../src/server/telemetry/config.ts');
const { registerBuiltinTelemetry } = await import('../src/server/telemetry/service.ts');
const { runProjectionPass } = await import('../src/server/telemetry/projection.ts');
const { listSeries } = await import('../src/server/telemetry/store.ts');
const { telemetryCatalogProblems } = await import('../src/shared/telemetry-catalog.ts');
after(() => { closeDb(); rmSync(home, { recursive: true, force: true }); });
test('health snapshots are off by default, bounded, declared and isolated by destination', () => {
  registerBuiltinTelemetry();
  assert.deepEqual(telemetryCatalogProblems(), []);
  captureTelemetryHealth();
  assert.equal(openDb().prepare('SELECT count(*) AS n FROM telemetry_journal').get()!.n, 0);
  const now = Date.now();
  assert.ok(setTelemetryConfig({ enabled: true, user: { enabled: true, endpoint: 'http://127.0.0.1:34318' } }, now).ok);
  captureTelemetryHealth(now); captureTelemetryHealth(now);
  const facts = openDb().prepare("SELECT facts_json FROM telemetry_journal WHERE name='mission.telemetry.health'").all();
  assert.equal(facts.length, 2, 'one local and one user fact in this cadence bucket');
  runProjectionPass(now);
  const user = listSeries(openDb(), 'user').filter((s) => s.instrument.startsWith('mission.telemetry.health.'));
  assert.equal(user.length, 9);
  assert.ok(user.every((s) => s.dimensions.profile === 'user'));
  assert.equal(user.find((s) => s.instrument.endsWith('.pending_bytes'))!.value, 0);
  assert.equal(listSeries(openDb(), 'product').length, 0);
});
