// GENERATED by scripts/codex-app-server-bindings.mjs from codex-cli 0.145.0.
// DO NOT EDIT. Run `node scripts/codex-app-server-bindings.mjs` against the pinned
// binary instead, and read the diff.
//
// The subset of `codex app-server generate-ts` that `harness/codex/sdk.ts` speaks - the
// transitive closure of the roots declared in that script, concatenated. Each declaration
// below is the generator's own output, byte for byte, with only its per-file header and
// its now-redundant `import type` lines removed.
//
// The protocol is EXPERIMENTAL upstream. Drift is absorbed by regenerating on a version
// bump, which is safe precisely because the adapter is the only consumer and it fails to
// compile when a field it reads moves.

/** The Codex build these bindings were generated from. */
export const CODEX_APP_SERVER_BINDINGS_VERSION = "0.145.0";

// ---- ClientInfo --------------------------------------------------------------------------

export type ClientInfo = { name: string, title: string | null, version: string, };

// ---- InitializeCapabilities --------------------------------------------------------------

/**
 * Client-declared capabilities negotiated during initialize.
 */
export type InitializeCapabilities = {
/**
 * Opt into receiving experimental API methods and fields.
 */
experimentalApi: boolean,
/**
 * Opt into `attestation/generate` requests for upstream `x-oai-attestation`.
 */
requestAttestation: boolean,
/**
 * Allow downstream MCP servers to request OpenAI extended form elicitations.
 */
mcpServerOpenaiFormElicitation?: boolean,
/**
 * Exact notification method names that should be suppressed for this
 * connection (for example `thread/started`).
 */
optOutNotificationMethods?: Array<string> | null, };

// ---- InitializeParams --------------------------------------------------------------------

export type InitializeParams = { clientInfo: ClientInfo, capabilities: InitializeCapabilities | null, };

// ---- AbsolutePathBuf ---------------------------------------------------------------------

/**
 * A path that is guaranteed to be absolute and normalized (though it is not
 * guaranteed to be canonicalized or exist on the filesystem).
 *
 * IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set
 * using [AbsolutePathBufGuard::new]. If no base path is set, the
 * deserialization will fail unless the path being deserialized is already
 * absolute.
 */
export type AbsolutePathBuf = string;

// ---- InitializeResponse ------------------------------------------------------------------

export type InitializeResponse = { userAgent: string,
/**
 * Absolute path to the server's $CODEX_HOME directory.
 */
codexHome: AbsolutePathBuf,
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platformFamily: string,
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platformOs: string, };

// ---- RequestId ---------------------------------------------------------------------------

export type RequestId = string | number;

// ---- LegacyAppPathString -----------------------------------------------------------------

/**
 * A UTF-8 path for preserving raw path compatibility at the app-server API
 * boundary while Codex migrates to [`PathUri`].
 *
 * Supports storing arbitrary strings read from the API and converting to and
 * from [`PathUri`] using an explicitly selected native path convention.
 *
 * When converting from [`PathUri`], "native" refers to the supplied
 * [`PathConvention`], which may be foreign to the operating system running
 * this process. The inner string is private so path-producing code must use a
 * path conversion method instead of bypassing the intended conversion
 * boundary. Non-UTF-8 paths are converted to UTF-8 lossily because this API
 * value is serialized as a JSON string.
 *
 * Deserialization and [`Self::from_string`] accept any UTF-8 string without
 * interpreting or validating it. Use [`Self::from_string`] when a caller
 * already owns legacy app-server path text and needs to preserve its wire
 * spelling; use [`Self::from_path`], [`Self::from_abs_path`], or
 * [`Self::from_path_uri`] when converting an actual path value. Relative
 * path text remains valid until an operation such as [`Self::to_path_uri`]
 * requires an absolute path.
 */
export type LegacyAppPathString = string;

// ---- v2/CommandAction --------------------------------------------------------------------

export type CommandAction = { "type": "read", command: string, name: string, path: AbsolutePathBuf, } | { "type": "listFiles", command: string, path: string | null, } | { "type": "search", command: string, query: string | null, path: string | null, } | { "type": "unknown", command: string, };

// ---- v2/ExecPolicyAmendment --------------------------------------------------------------

export type ExecPolicyAmendment = Array<string>;

// ---- v2/NetworkApprovalProtocol ----------------------------------------------------------

export type NetworkApprovalProtocol = "http" | "https" | "socks5Tcp" | "socks5Udp";

// ---- v2/NetworkApprovalContext -----------------------------------------------------------

export type NetworkApprovalContext = { host: string, protocol: NetworkApprovalProtocol, };

// ---- v2/NetworkPolicyRuleAction ----------------------------------------------------------

export type NetworkPolicyRuleAction = "allow" | "deny";

// ---- v2/NetworkPolicyAmendment -----------------------------------------------------------

export type NetworkPolicyAmendment = { host: string, action: NetworkPolicyRuleAction, };

// ---- v2/CommandExecutionRequestApprovalParams --------------------------------------------

export type CommandExecutionRequestApprovalParams = {threadId: string, turnId: string, itemId: string, /**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
startedAtMs: number, /**
 * Unique identifier for this specific approval callback.
 *
 * For regular shell/unified_exec approvals, this is null.
 *
 * For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to
 * one parent `itemId`, so `approvalId` is a distinct opaque callback id
 * (a UUID) used to disambiguate routing.
 */
approvalId?: string | null, /**
 * Environment in which the command will run.
 */
environmentId: string | null, /**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, /**
 * Optional context for a managed-network approval prompt.
 */
networkApprovalContext?: NetworkApprovalContext | null, /**
 * The command to be executed.
 */
command?: string | null, /**
 * The command's working directory.
 */
cwd?: LegacyAppPathString | null, /**
 * Best-effort parsed command actions for friendly display.
 */
commandActions?: Array<CommandAction> | null, /**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposedExecpolicyAmendment?: ExecPolicyAmendment | null, /**
 * Optional proposed network policy amendments (allow/deny host) for future requests.
 */
proposedNetworkPolicyAmendments?: Array<NetworkPolicyAmendment> | null};

// ---- v2/CommandExecutionApprovalDecision -------------------------------------------------

export type CommandExecutionApprovalDecision = "accept" | "acceptForSession" | { "acceptWithExecpolicyAmendment": { execpolicy_amendment: ExecPolicyAmendment, } } | { "applyNetworkPolicyAmendment": { network_policy_amendment: NetworkPolicyAmendment, } } | "decline" | "cancel";

// ---- v2/CommandExecutionRequestApprovalResponse ------------------------------------------

export type CommandExecutionRequestApprovalResponse = { decision: CommandExecutionApprovalDecision, };

// ---- v2/NonSteerableTurnKind -------------------------------------------------------------

export type NonSteerableTurnKind = "review" | "compact";

// ---- v2/CodexErrorInfo -------------------------------------------------------------------

/**
 * This translation layer make sure that we expose codex error code in camel case.
 *
 * When an upstream HTTP status is available (for example, from the Responses API or a provider),
 * it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
 */
export type CodexErrorInfo = "contextWindowExceeded" | "sessionBudgetExceeded" | "usageLimitExceeded" | "serverOverloaded" | "cyberPolicy" | { "httpConnectionFailed": { httpStatusCode: number | null, } } | { "responseStreamConnectionFailed": { httpStatusCode: number | null, } } | "internalServerError" | "unauthorized" | "badRequest" | "threadRollbackFailed" | "sandboxError" | { "responseStreamDisconnected": { httpStatusCode: number | null, } } | { "responseTooManyFailedAttempts": { httpStatusCode: number | null, } } | { "activeTurnNotSteerable": { turnKind: NonSteerableTurnKind, } } | "other";

// ---- v2/TurnError ------------------------------------------------------------------------

export type TurnError = { message: string, codexErrorInfo: CodexErrorInfo | null, additionalDetails: string | null, };

// ---- v2/ErrorNotification ----------------------------------------------------------------

export type ErrorNotification = { error: TurnError, willRetry: boolean, threadId: string, turnId: string, };

// ---- v2/FileChangeRequestApprovalParams --------------------------------------------------

export type FileChangeRequestApprovalParams = { threadId: string, turnId: string, itemId: string,
/**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
startedAtMs: number,
/**
 * Optional explanatory reason (e.g. request for extra write access).
 */
reason?: string | null,
/**
 * [UNSTABLE] When set, the agent is asking the user to allow writes under this root
 * for the remainder of the session (unclear if this is honored today).
 */
grantRoot?: string | null, };

// ---- v2/FileChangeApprovalDecision -------------------------------------------------------

export type FileChangeApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

// ---- v2/FileChangeRequestApprovalResponse ------------------------------------------------

export type FileChangeRequestApprovalResponse = { decision: FileChangeApprovalDecision, };

// ---- ImageGenerationItem -----------------------------------------------------------------

export type ImageGenerationItem = { id: string, status: string, revisedPrompt: string | null, result: string, savedPath?: AbsolutePathBuf, };

// ---- MessagePhase ------------------------------------------------------------------------

/**
 * Classifies an assistant message as interim commentary or final answer text.
 *
 * Providers do not emit this consistently, so callers must treat `None` as
 * "phase unknown" and keep compatibility behavior for legacy models.
 */
export type MessagePhase = "commentary" | "final_answer";

// ---- ReasoningEffort ---------------------------------------------------------------------

/**
 * See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-reasoning
 */
export type ReasoningEffort = string;

// ---- SleepItem ---------------------------------------------------------------------------

/**
 * Display item emitted by the interruptible `clock.sleep` tool.
 */
export type SleepItem = { id: string, durationMs: number, };

// ---- serde_json/JsonValue ----------------------------------------------------------------

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

// ---- v2/WebSearchAction ------------------------------------------------------------------

export type WebSearchAction = { "type": "search", query: string | null, queries: Array<string> | null, } | { "type": "openPage", url: string | null, } | { "type": "findInPage", url: string | null, pattern: string | null, } | { "type": "other" };

// ---- WebSearchItem -----------------------------------------------------------------------

export type WebSearchItem = { id: string, query: string, action: WebSearchAction | null,
/**
 * Structured search results returned out-of-band by standalone web search.
 *
 * These stay as opaque JSON at the extension/app-server boundary so new
 * result fields and result types can pass through without a Codex release.
 */
results: Array<JsonValue> | null, };

// ---- v2/CollabAgentStatus ----------------------------------------------------------------

export type CollabAgentStatus = "pendingInit" | "running" | "interrupted" | "completed" | "errored" | "shutdown" | "notFound";

// ---- v2/CollabAgentState -----------------------------------------------------------------

export type CollabAgentState = { status: CollabAgentStatus, message: string | null, };

// ---- v2/CollabAgentTool ------------------------------------------------------------------

export type CollabAgentTool = "spawnAgent" | "sendInput" | "resumeAgent" | "wait" | "closeAgent";

// ---- v2/CollabAgentToolCallStatus --------------------------------------------------------

export type CollabAgentToolCallStatus = "inProgress" | "completed" | "failed";

// ---- v2/CommandExecutionSource -----------------------------------------------------------

export type CommandExecutionSource = "agent" | "userShell" | "unifiedExecStartup" | "unifiedExecInteraction";

// ---- v2/CommandExecutionStatus -----------------------------------------------------------

export type CommandExecutionStatus = "inProgress" | "completed" | "failed" | "declined";

// ---- v2/DynamicToolCallOutputContentItem -------------------------------------------------

export type DynamicToolCallOutputContentItem = { "type": "inputText", text: string, } | { "type": "inputImage", imageUrl: string, } | { "type": "inputAudio", audioUrl: string, };

// ---- v2/DynamicToolCallStatus ------------------------------------------------------------

export type DynamicToolCallStatus = "inProgress" | "completed" | "failed";

// ---- v2/PatchChangeKind ------------------------------------------------------------------

export type PatchChangeKind = { "type": "add" } | { "type": "delete" } | { "type": "update", move_path: string | null, };

// ---- v2/FileUpdateChange -----------------------------------------------------------------

export type FileUpdateChange = { path: string, kind: PatchChangeKind, diff: string, };

// ---- v2/HookPromptFragment ---------------------------------------------------------------

export type HookPromptFragment = { text: string, hookRunId: string, };

// ---- v2/McpToolCallAppContext ------------------------------------------------------------

export type McpToolCallAppContext = { connectorId: string, linkId: string | null, resourceUri: string | null, appName: string | null, actionName: string | null, };

// ---- v2/McpToolCallError -----------------------------------------------------------------

export type McpToolCallError = { message: string, };

// ---- v2/McpToolCallResult ----------------------------------------------------------------

export type McpToolCallResult = { content: Array<JsonValue>, structuredContent: JsonValue | null, _meta: JsonValue | null, };

// ---- v2/McpToolCallStatus ----------------------------------------------------------------

export type McpToolCallStatus = "inProgress" | "completed" | "failed";

// ---- v2/MemoryCitationEntry --------------------------------------------------------------

export type MemoryCitationEntry = { path: string, lineStart: number, lineEnd: number, note: string, };

// ---- v2/MemoryCitation -------------------------------------------------------------------

export type MemoryCitation = { entries: Array<MemoryCitationEntry>, threadIds: Array<string>, };

// ---- v2/PatchApplyStatus -----------------------------------------------------------------

export type PatchApplyStatus = "inProgress" | "completed" | "failed" | "declined";

// ---- v2/SubAgentActivityKind -------------------------------------------------------------

export type SubAgentActivityKind = "started" | "interacted" | "interrupted";

// ---- ImageDetail -------------------------------------------------------------------------

export type ImageDetail = "auto" | "low" | "high" | "original";

// ---- v2/ByteRange ------------------------------------------------------------------------

export type ByteRange = { start: number, end: number, };

// ---- v2/TextElement ----------------------------------------------------------------------

export type TextElement = {
/**
 * Byte range in the parent `text` buffer that this element occupies.
 */
byteRange: ByteRange,
/**
 * Optional human-readable placeholder for the element, displayed in the UI.
 */
placeholder: string | null, };

// ---- v2/UserInput ------------------------------------------------------------------------

export type UserInput = { "type": "text", text: string,
/**
 * UI-defined spans within `text` used to render or persist special elements.
 */
text_elements: Array<TextElement>, } | { "type": "image", detail?: ImageDetail, url: string, } | { "type": "localImage", detail?: ImageDetail, path: string, } | { "type": "audio", url: string, } | { "type": "localAudio", path: string, } | { "type": "skill", name: string, path: string, } | { "type": "mention", name: string, path: string, };

// ---- v2/ThreadItem -----------------------------------------------------------------------

export type ThreadItem = { "type": "userMessage", id: string, clientId: string | null, content: Array<UserInput>, } | { "type": "hookPrompt", id: string, fragments: Array<HookPromptFragment>, } | { "type": "agentMessage", id: string, text: string, phase: MessagePhase | null, memoryCitation: MemoryCitation | null, } | { "type": "plan", id: string, text: string, } | { "type": "reasoning", id: string, summary: Array<string>, content: Array<string>, } | { "type": "commandExecution", id: string,
/**
 * The command to be executed.
 */
command: string,
/**
 * The command's working directory.
 */
cwd: LegacyAppPathString,
/**
 * Identifier for the underlying PTY process (when available).
 */
processId: string | null, source: CommandExecutionSource, status: CommandExecutionStatus,
/**
 * A best-effort parsing of the command to understand the action(s) it will perform.
 * This returns a list of CommandAction objects because a single shell command may
 * be composed of many commands piped together.
 */
commandActions: Array<CommandAction>,
/**
 * The command's output, aggregated from stdout and stderr.
 */
aggregatedOutput: string | null,
/**
 * The command's exit code.
 */
exitCode: number | null,
/**
 * The duration of the command execution in milliseconds.
 */
durationMs: number | null, } | { "type": "fileChange", id: string, changes: Array<FileUpdateChange>, status: PatchApplyStatus, } | { "type": "mcpToolCall", id: string, server: string, tool: string, status: McpToolCallStatus, arguments: JsonValue, appContext: McpToolCallAppContext | null,
/**
 * Deprecated: use `appContext.resourceUri` instead.
 */
mcpAppResourceUri?: string, pluginId: string | null, result: McpToolCallResult | null, error: McpToolCallError | null,
/**
 * The duration of the MCP tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "dynamicToolCall", id: string, namespace: string | null, tool: string, arguments: JsonValue, status: DynamicToolCallStatus, contentItems: Array<DynamicToolCallOutputContentItem> | null, success: boolean | null,
/**
 * The duration of the dynamic tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "collabAgentToolCall",
/**
 * Unique identifier for this collab tool call.
 */
id: string,
/**
 * Name of the collab tool that was invoked.
 */
tool: CollabAgentTool,
/**
 * Current status of the collab tool call.
 */
status: CollabAgentToolCallStatus,
/**
 * Thread ID of the agent issuing the collab request.
 */
senderThreadId: string,
/**
 * Thread ID of the receiving agent, when applicable. In case of spawn operation,
 * this corresponds to the newly spawned agent.
 */
receiverThreadIds: Array<string>,
/**
 * Prompt text sent as part of the collab tool call, when available.
 */
prompt: string | null,
/**
 * Model requested for the spawned agent, when applicable.
 */
model: string | null,
/**
 * Reasoning effort requested for the spawned agent, when applicable.
 */
reasoningEffort: ReasoningEffort | null,
/**
 * Last known status of the target agents, when available.
 */
agentsStates: { [key in string]?: CollabAgentState }, } | { "type": "subAgentActivity", id: string, kind: SubAgentActivityKind, agentThreadId: string, agentPath: string, } | { "type": "webSearch" } & WebSearchItem | { "type": "imageView", id: string, path: LegacyAppPathString, } | { "type": "sleep" } & SleepItem | { "type": "imageGeneration" } & ImageGenerationItem | { "type": "enteredReviewMode", id: string, review: string, } | { "type": "exitedReviewMode", id: string, review: string, } | { "type": "contextCompaction", id: string, };

// ---- v2/ItemCompletedNotification --------------------------------------------------------

export type ItemCompletedNotification = { item: ThreadItem, threadId: string, turnId: string,
/**
 * Unix timestamp (in milliseconds) when this item lifecycle completed.
 */
completedAtMs: number, };

// ---- v2/ItemStartedNotification ----------------------------------------------------------

export type ItemStartedNotification = { item: ThreadItem, threadId: string, turnId: string,
/**
 * Unix timestamp (in milliseconds) when this item lifecycle started.
 */
startedAtMs: number, };

// ---- Personality -------------------------------------------------------------------------

export type Personality = "none" | "friendly" | "pragmatic";

// ---- v2/ApprovalsReviewer ----------------------------------------------------------------

/**
 * Configures who approval requests are routed to for review. Examples
 * include sandbox escapes, blocked network access, MCP approval prompts, and
 * ARC escalations. Defaults to `user`. `auto_review` uses a carefully
 * prompted subagent to gather relevant context and apply a risk-based
 * decision framework before approving or denying the request.
 */
export type ApprovalsReviewer = "user" | "auto_review" | "guardian_subagent";

// ---- v2/AskForApproval -------------------------------------------------------------------

export type AskForApproval = "untrusted" | "on-request" | { "granular": { sandbox_approval: boolean, rules: boolean, skill_approval: boolean, request_permissions: boolean, mcp_elicitations: boolean, } } | "never";

// ---- v2/SandboxMode ----------------------------------------------------------------------

export type SandboxMode = "read-only" | "workspace-write" | "danger-full-access";

// ---- v2/ThreadResumeParams ---------------------------------------------------------------

/**
 * There are three ways to resume a thread:
 * 1. By thread_id: load the thread from disk by thread_id and resume it.
 * 2. By history: instantiate the thread from memory and resume it.
 * 3. By path: load the thread from disk by path and resume it.
 *
 * For non-running threads, the precedence is: history > non-empty path > thread_id.
 * If using history or a non-empty path for a non-running thread, the thread_id
 * param will be ignored.
 *
 * If thread_id identifies a running thread, app-server rejoins that thread and
 * treats a non-empty path as a consistency check against the active rollout path.
 * Empty string path values are treated as absent.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadResumeParams = {threadId: string, /**
 * Configuration overrides for the resumed thread, if any.
 */
model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this thread
 * and subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null};

// ---- v2/NetworkAccess --------------------------------------------------------------------

export type NetworkAccess = "restricted" | "enabled";

// ---- v2/SandboxPolicy --------------------------------------------------------------------

export type SandboxPolicy = { "type": "dangerFullAccess" } | { "type": "readOnly", networkAccess: boolean, } | { "type": "externalSandbox", networkAccess: NetworkAccess, } | { "type": "workspaceWrite", writableRoots: Array<AbsolutePathBuf>, networkAccess: boolean, excludeTmpdirEnvVar: boolean, excludeSlashTmp: boolean, };

// ---- v2/GitInfo --------------------------------------------------------------------------

export type GitInfo = { sha: string | null, branch: string | null, originUrl: string | null, };

// ---- AgentPath ---------------------------------------------------------------------------

export type AgentPath = string;

// ---- ThreadId ----------------------------------------------------------------------------

/**
 * Identifier for a Codex thread.
 *
 * Codex-generated thread IDs are UUIDv7, and some use cases rely on that.
 */
export type ThreadId = string;

// ---- SubAgentSource ----------------------------------------------------------------------

export type SubAgentSource = "review" | "compact" | { "thread_spawn": { parent_thread_id: ThreadId, depth: number, agent_path: AgentPath | null, agent_nickname: string | null, agent_role: string | null, } } | "memory_consolidation" | { "other": string };

// ---- v2/SessionSource --------------------------------------------------------------------

export type SessionSource = "cli" | "vscode" | "exec" | "appServer" | { "custom": string } | { "subAgent": SubAgentSource } | "unknown";

// ---- v2/ThreadSource ---------------------------------------------------------------------

export type ThreadSource = string;

// ---- v2/ThreadActiveFlag -----------------------------------------------------------------

export type ThreadActiveFlag = "waitingOnApproval" | "waitingOnUserInput";

// ---- v2/ThreadStatus ---------------------------------------------------------------------

export type ThreadStatus = { "type": "notLoaded" } | { "type": "idle" } | { "type": "systemError" } | { "type": "active", activeFlags: Array<ThreadActiveFlag>, };

// ---- v2/TurnItemsView --------------------------------------------------------------------

export type TurnItemsView = "notLoaded" | "summary" | "full";

// ---- v2/TurnStatus -----------------------------------------------------------------------

export type TurnStatus = "completed" | "interrupted" | "failed" | "inProgress";

// ---- v2/Turn -----------------------------------------------------------------------------

export type Turn = {
/**
 * Identifier for this turn. Codex-generated turn IDs are UUIDv7.
 */
id: string,
/**
 * Thread items currently included in this turn payload.
 */
items: Array<ThreadItem>,
/**
 * Describes how much of `items` has been loaded for this turn.
 */
itemsView: TurnItemsView, status: TurnStatus,
/**
 * Only populated when the Turn's status is failed.
 */
error: TurnError | null,
/**
 * Unix timestamp (in seconds) when the turn started.
 */
startedAt: number | null,
/**
 * Unix timestamp (in seconds) when the turn completed.
 */
completedAt: number | null,
/**
 * Duration between turn start and completion in milliseconds, if known.
 */
durationMs: number | null, };

// ---- v2/Thread ---------------------------------------------------------------------------

export type Thread = {/**
 * Identifier for this thread. Codex-generated thread IDs are UUIDv7.
 */
id: string, /**
 * Session id shared by threads that belong to the same session tree.
 */
sessionId: string, /**
 * Source thread id when this thread was created by forking another thread.
 */
forkedFromId: string | null, /**
 * The ID of the parent thread. This will only be set if this thread is a subagent.
 */
parentThreadId: string | null, /**
 * Usually the first user message in the thread, if available.
 */
preview: string, /**
 * Whether the thread is ephemeral and should not be materialized on disk.
 */
ephemeral: boolean, /**
 * Model provider used for this thread (for example, 'openai').
 */
modelProvider: string, /**
 * Unix timestamp (in seconds) when the thread was created.
 */
createdAt: number, /**
 * Unix timestamp (in seconds) when the thread was last updated.
 */
updatedAt: number, /**
 * Unix timestamp (in seconds) used for thread recency ordering.
 */
recencyAt: number | null, /**
 * Current runtime status for the thread.
 */
status: ThreadStatus, /**
 * [UNSTABLE] Path to the thread on disk.
 */
path: string | null, /**
 * Working directory captured for the thread.
 */
cwd: AbsolutePathBuf, /**
 * Version of the CLI that created the thread.
 */
cliVersion: string, /**
 * Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
 */
source: SessionSource, /**
 * Optional analytics source classification for this thread.
 */
threadSource: ThreadSource | null, /**
 * Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
 */
agentNickname: string | null, /**
 * Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
 */
agentRole: string | null, /**
 * Optional Git metadata captured when the thread was created.
 */
gitInfo: GitInfo | null, /**
 * Optional user-facing thread title.
 */
name: string | null, /**
 * Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read`
 * (when `includeTurns` is true) responses.
 * For all other responses and notifications returning a Thread,
 * the turns field will be an empty list.
 */
turns: Array<Turn>};

// ---- v2/ThreadResumeResponse -------------------------------------------------------------

export type ThreadResumeResponse = {thread: Thread, model: string, modelProvider: string, serviceTier: string | null, cwd: AbsolutePathBuf, /**
 * Environment-native paths to instruction source files currently loaded for this thread.
 */
instructionSources: Array<LegacyAppPathString>, approvalPolicy: AskForApproval, /**
 * Reviewer currently used for approval requests on this thread.
 */
approvalsReviewer: ApprovalsReviewer, /**
 * Legacy sandbox policy retained for compatibility. Experimental clients
 * should prefer `activePermissionProfile` for profile provenance.
 */
sandbox: SandboxPolicy, reasoningEffort: ReasoningEffort | null};

// ---- v2/ThreadStartSource ----------------------------------------------------------------

export type ThreadStartSource = "startup" | "clear";

// ---- v2/ThreadStartParams ----------------------------------------------------------------

export type ThreadStartParams = {model?: string | null, modelProvider?: string | null, serviceTier?: string | null | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this thread
 * and subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, serviceName?: string | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null, ephemeral?: boolean | null, sessionStartSource?: ThreadStartSource | null, /**
 * Optional client-supplied analytics source classification for this thread.
 */
threadSource?: ThreadSource | null};

// ---- v2/ThreadStartResponse --------------------------------------------------------------

export type ThreadStartResponse = {thread: Thread, model: string, modelProvider: string, serviceTier: string | null, cwd: AbsolutePathBuf, /**
 * Environment-native paths to instruction source files currently loaded for this thread.
 */
instructionSources: Array<LegacyAppPathString>, approvalPolicy: AskForApproval, /**
 * Reviewer currently used for approval requests on this thread.
 */
approvalsReviewer: ApprovalsReviewer, /**
 * Legacy sandbox policy retained for compatibility. Experimental clients
 * should prefer `activePermissionProfile` for profile provenance.
 */
sandbox: SandboxPolicy, reasoningEffort: ReasoningEffort | null};

// ---- v2/ThreadStartedNotification --------------------------------------------------------

export type ThreadStartedNotification = { thread: Thread, };

// ---- v2/ThreadStatusChangedNotification --------------------------------------------------

export type ThreadStatusChangedNotification = { threadId: string, status: ThreadStatus, };

// ---- v2/TokenUsageBreakdown --------------------------------------------------------------

export type TokenUsageBreakdown = { totalTokens: number, inputTokens: number, cachedInputTokens: number, cacheWriteInputTokens: number, outputTokens: number, reasoningOutputTokens: number, };

// ---- v2/ThreadTokenUsage -----------------------------------------------------------------

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null, };

// ---- v2/ThreadTokenUsageUpdatedNotification ----------------------------------------------

export type ThreadTokenUsageUpdatedNotification = { threadId: string, turnId: string, tokenUsage: ThreadTokenUsage, };

// ---- v2/ToolRequestUserInputOption -------------------------------------------------------

/**
 * EXPERIMENTAL. Defines a single selectable option for request_user_input.
 */
export type ToolRequestUserInputOption = { label: string, description: string, };

// ---- v2/ToolRequestUserInputQuestion -----------------------------------------------------

/**
 * EXPERIMENTAL. Represents one request_user_input question and its required options.
 */
export type ToolRequestUserInputQuestion = { id: string, header: string, question: string, isOther: boolean, isSecret: boolean, options: Array<ToolRequestUserInputOption> | null, };

// ---- v2/ToolRequestUserInputParams -------------------------------------------------------

/**
 * EXPERIMENTAL. Params sent with a request_user_input event.
 */
export type ToolRequestUserInputParams = { threadId: string, turnId: string, itemId: string, questions: Array<ToolRequestUserInputQuestion>, autoResolutionMs: number | null, };

// ---- v2/ToolRequestUserInputAnswer -------------------------------------------------------

/**
 * EXPERIMENTAL. Captures a user's answer to a request_user_input question.
 */
export type ToolRequestUserInputAnswer = { answers: Array<string>, };

// ---- v2/ToolRequestUserInputResponse -----------------------------------------------------

/**
 * EXPERIMENTAL. Response payload mapping question ids to answers.
 */
export type ToolRequestUserInputResponse = { answers: { [key in string]?: ToolRequestUserInputAnswer }, };

// ---- v2/TurnCompletedNotification --------------------------------------------------------

export type TurnCompletedNotification = { threadId: string, turn: Turn, };

// ---- v2/TurnInterruptParams --------------------------------------------------------------

export type TurnInterruptParams = { threadId: string, turnId: string, };

// ---- v2/TurnInterruptResponse ------------------------------------------------------------

export type TurnInterruptResponse = Record<string, never>;

// ---- ReasoningSummary --------------------------------------------------------------------

/**
 * A summary of the reasoning performed by the model. This can be useful for
 * debugging and understanding the model's reasoning process.
 * See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
 */
export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

// ---- v2/TurnStartParams ------------------------------------------------------------------

export type TurnStartParams = {threadId: string, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Override the working directory for this turn and subsequent turns.
 */
cwd?: string | null, /**
 * Override the approval policy for this turn and subsequent turns.
 */
approvalPolicy?: AskForApproval | null, /**
 * Override where approval requests are routed for review on this turn and
 * subsequent turns.
 */
approvalsReviewer?: ApprovalsReviewer | null, /**
 * Override the sandbox policy for this turn and subsequent turns.
 */
sandboxPolicy?: SandboxPolicy | null, /**
 * Override the model for this turn and subsequent turns.
 */
model?: string | null, /**
 * Override the service tier for this turn and subsequent turns.
 */
serviceTier?: string | null | null, /**
 * Override the reasoning effort for this turn and subsequent turns.
 */
effort?: ReasoningEffort | null, /**
 * Override the reasoning summary for this turn and subsequent turns.
 */
summary?: ReasoningSummary | null, /**
 * Override the personality for this turn and subsequent turns.
 */
personality?: Personality | null, /**
 * Optional JSON Schema used to constrain the final assistant message for
 * this turn.
 */
outputSchema?: JsonValue | null};

// ---- v2/TurnStartResponse ----------------------------------------------------------------

export type TurnStartResponse = { turn: Turn, };

// ---- v2/TurnStartedNotification ----------------------------------------------------------

export type TurnStartedNotification = { threadId: string, turn: Turn, };

// ---- v2/TurnSteerParams ------------------------------------------------------------------

export type TurnSteerParams = {threadId: string, clientUserMessageId?: string | null, input: Array<UserInput>, /**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expectedTurnId: string};

// ---- v2/TurnSteerResponse ----------------------------------------------------------------

export type TurnSteerResponse = { turnId: string, };
