import { join, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ARTIFACTS_ROOT = fileURLToPath(new URL("../.artifacts/", import.meta.url));

/**
 * Returns a gitignored destination for review evidence generated by an e2e spec.
 *
 * Callers create the topic directory only when capture is explicitly enabled. The trailing
 * separator preserves the existing capture helpers' `${dir}${filename}` convention.
 */
export function artifactsDir(topic: string): string {
  return `${join(ARTIFACTS_ROOT, topic)}${sep}`;
}
