/** Audited operations owned by earlier phases or explicitly excluded from action counts. */
export const ACTION_EXCLUSIONS = [
  ["POST", "/mcp/plan-publication", "Read-only plan-publication ownership query; no plan is published by this operation."],
  ["POST", "/api/sessions/:id/workflow-review", "Phase 4 owns workflow run/submission facts through the WorkflowStore mutation observer."],
  ["POST", "/api/sessions/:id/html-block-anchor", "Read-only renderer handshake; Files entry/preview owns intentional use."],
  ["POST", "/api/sessions/:id/html-block-target", "Read-only renderer handshake; Files entry/preview owns intentional use."],
  ["POST", "/hooks/:event", "Phase 3 normalized session observations; raw hook delivery is not a primary action."],
  ["POST", "/statusline", "Phase 3 observed execution metadata; status refresh is not feature use."],
  ["POST", "/ingest/conductor", "Provider notifications are reconciled at the normalized pipeline owner; ingest traffic is not a second action."],
  ["POST", "/v1/metrics", "Existing agent cost receiver; Phase 3 owns deduplicated usage."],
  ["POST", "/mcp/status", "Presence/status refresh, not intentional feature use."],
  ["POST", "/api/sessions/:id/composer-activity", "High-frequency typing/liveness signal; explicitly excluded from activity telemetry."],
  ["POST", "/api/sessions/:id/send", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/select-option", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/submit-options", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/handoff", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/inject", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/pending-turns/:turnId/recall", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/kill", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/interrupt", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/effort", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/sessions/:id/reset", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/foreman/planner/control/claim", "Worker lease acquisition; not a completed plan or feature use."],
  ["POST", "/api/foreman/planner/health", "Heartbeat/health refresh; no adoption count."],
  ["POST", "/api/foreman/heartbeat", "Worker liveness lease; no adoption count."],
  ["POST", "/api/foreman/heartbeat/release", "Worker liveness lease release; no adoption count."],
  ["POST", "/api/usage/automation", "Phase 3 owns deduplicated automation spend, not another automation action."],
  ["PUT", "/api/telemetry/config", "Phase 2 telemetry controls/typed ingress; excluded from recursive primary-action and error capture."],
  ["POST", "/api/telemetry/operation", "Phase 2 telemetry controls/typed ingress; excluded from recursive primary-action and error capture."],
  ["POST", "/api/telemetry/probe", "Phase 2 telemetry controls/typed ingress; excluded from recursive primary-action and error capture."],
  ["POST", "/api/telemetry/drain", "Phase 2 telemetry controls/typed ingress; excluded from recursive primary-action and error capture."],
  ["POST", "/api/telemetry/ingress", "Phase 2 telemetry controls/typed ingress; excluded from recursive primary-action and error capture."],
  ["POST", "/api/tasks/:id/dispatch", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/tasks/:id/assign", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/tasks/:id/cancel", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
  ["POST", "/api/tasks/:id/complete", "Phase 3 session/dispatch/task owner already records this outcome; add request surface only."],
] as const;
