#!/usr/bin/env node
// Regenerate `src/server/workflows/builtin-session-actions.generated.ts` from
// `docs/session-actions/*.md`.
//
//   npm run session-actions
//
// The exact sibling of `builtin-personas.ts`, sharing its reader and renderer, for the same
// reason that script is TypeScript: `builtin-session-actions.test.ts` imports the two
// functions below to prove the committed module is exactly what regenerating produces.
//
// Run this after editing, adding or removing a SessionAction document, and commit the result.
//
// The prompt text is the ONE thing a SessionAction delivers, so exactness here is not a
// nicety: the generated bytes become the packet a session receives and the snapshot a
// published version freezes.
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { builtinMarkdownSources, renderBuiltinMarkdownModule } from "./builtin-markdown.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = join(root, "docs", "session-actions");
const outFile = join(root, "src", "server", "workflows", "builtin-session-actions.generated.ts");

const SPEC = {
  script: "scripts/builtin-session-actions.ts",
  sourceGlob: "docs/session-actions/*.md",
  command: "npm run session-actions",
  constName: "BUILTIN_SESSION_ACTION_SOURCES",
  field: "promptMarkdown",
  doc: "/** The exact bytes of each shipped SessionAction document, in filename order. */",
} as const;

export interface BuiltinSessionActionSource {
  slug: string;
  promptMarkdown: string;
}

/** The slug is the filename, and it is the durable half of the built-in's id. */
export function builtinSessionActionSources(dir = sourceDir): BuiltinSessionActionSource[] {
  return builtinMarkdownSources(dir)
    .map((source) => ({ slug: source.slug, promptMarkdown: source.markdown }));
}

export function renderBuiltinSessionActionModule(
  sources: readonly BuiltinSessionActionSource[],
): string {
  return renderBuiltinMarkdownModule(
    SPEC,
    sources.map((source) => ({ slug: source.slug, markdown: source.promptMarkdown })),
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const sources = builtinSessionActionSources();
  writeFileSync(outFile, renderBuiltinSessionActionModule(sources));
  console.log(
    `Wrote ${sources.length} built-in session action${sources.length === 1 ? "" : "s"} to ${outFile}`,
  );
}
