#!/usr/bin/env node
// Regenerate `src/server/workflows/builtin-session-actions.generated.ts` from `actions/*.md`.
//
//   npm run session-actions
//
// The exact sibling of `builtin-personas.ts`, sharing its reader and renderer, for the same
// reason that script is TypeScript: `builtin-session-actions.test.ts` imports the two
// functions below to prove the committed module is exactly what regenerating produces.
//
// Run this after editing, adding or removing a SessionAction document, and commit the result.
//
// The prompt text is the ONE thing a SessionAction delivers, so exactness here is not a
// nicety: the generated bytes become the packet a session receives and the snapshot a
// published version freezes.
import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { builtinMarkdownSources, renderBuiltinMarkdownModule } from "./builtin-markdown.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = join(root, "actions");
const outFile = join(root, "src", "server", "workflows", "builtin-session-actions.generated.ts");

/**
 * The documents in `actions/` that are NOT session actions, so this generator skips them.
 *
 * Only `README.md`, which explains what the directory is - a root `actions/` reads as GitHub
 * Actions at first glance, so that prose is load-bearing rather than decorative. Because this
 * generator globs the whole directory, the explanation itself needs an exclusion: without it
 * an upgrade would add `builtin:README` to the catalog as a session action that would type the
 * directory's own documentation into an operator's conversation.
 *
 * A list of filenames rather than a naming heuristic, for the reason `builtinMarkdownSources`
 * gives: a name that is not on the list shows up in the generated module and in the drift
 * test, where a heuristic would silently misclassify a new document.
 *
 * Exported so `test/builtin-session-actions.test.ts` can hold the same list against the
 * directory rather than restating it: a second copy would agree with itself while the
 * generator shipped something else.
 */
export const NON_SESSION_ACTION_DOCUMENTS = ["README.md"] as const;

const SPEC = {
  script: "scripts/builtin-session-actions.ts",
  sourceGlob: "actions/*.md",
  command: "npm run session-actions",
  constName: "BUILTIN_SESSION_ACTION_SOURCES",
  field: "promptMarkdown",
  doc: "/** The exact bytes of each shipped SessionAction document, in filename order. */",
} as const;

export interface BuiltinSessionActionSource {
  slug: string;
  promptMarkdown: string;
}

/** The slug is the filename, and it is the durable half of the built-in's id. */
export function builtinSessionActionSources(dir = sourceDir): BuiltinSessionActionSource[] {
  return builtinMarkdownSources(dir, NON_SESSION_ACTION_DOCUMENTS)
    .map((source) => ({ slug: source.slug, promptMarkdown: source.markdown }));
}

export function renderBuiltinSessionActionModule(
  sources: readonly BuiltinSessionActionSource[],
): string {
  return renderBuiltinMarkdownModule(
    SPEC,
    sources.map((source) => ({ slug: source.slug, markdown: source.promptMarkdown })),
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const sources = builtinSessionActionSources();
  writeFileSync(outFile, renderBuiltinSessionActionModule(sources));
  console.log(
    `Wrote ${sources.length} built-in session action${sources.length === 1 ? "" : "s"} to ${outFile}`,
  );
}
